/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "wildrydesba9c4d49_userpool_ba9c4d49-main",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_JljYziOkW",
    "oauth": {},
    "aws_user_pools_web_client_id": "16mecc9pc7g0d8s0b9hkl4av62",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};

export default awsmobile;
